/****** Object:  Table [dbo].[WU_Role]    Script Date: 16/04/2019 11:28:47 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WU_Role](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](128) NULL,
 CONSTRAINT [PK_WU_Role] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
